# permissions for end users to view pacevalcomputationobjects.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: pacevalcomputationobject-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
  name: pacevalcomputationobject-viewer-role
rules:
- apiGroups:
  - paceval.com
  resources:
  - pacevalcomputationobjects
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - paceval.com
  resources:
  - pacevalcomputationobjects/status
  verbs:
  - get
